# -*- coding: utf-8 -*-
# vim: ft=yaml
---
name: main
'on': [push, pull_request]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  pre-commit:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.0
        with:
          extra_args: --verbose --all-files
  kitchen:
    runs-on: windows-latest
    env:
      machine_user: kitchen
      machine_pass: Pass@word1
      machine_port: 5985
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - shell: powershell
        run: |
          $password = ConvertTo-SecureString $env:machine_pass -AsPlainText -Force
          New-LocalUser $env:machine_user -Password $password
          Add-LocalGroupMember -Group "Administrators" -Member $env:machine_user
      - shell: powershell
        run: >
          Set-WSManQuickConfig -Force;
          Set-WSManInstance -ResourceURI winrm/config/service
          -ValueSet @{AllowUnencrypted="true"}
      - run: gem install bundler --quiet --no-document
      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - run: bundle exec kitchen test
        env:
          KITCHEN_LOCAL_YAML: kitchen.github.yml
          CHEF_LICENSE: accept-no-persist
  release:
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    needs: [commitlint, pre-commit, kitchen]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15'
      - uses: cycjimmy/semantic-release-action@v2
        with:
          branch: master
          extra_plugins: |
            @semantic-release/changelog@3
            @semantic-release/exec@3
            @semantic-release/git@7
          semantic_version: 15.14
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
